# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certsponge < Formula
  desc "Utility for splitting Vault's PKI output into one or more files containing the private key, certificate, and CA data"
  homepage "https://github.com/joemiller/certsponge"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.1/certsponge_darwin_amd64.tar.gz"
      sha256 "a01000253dd73952c454e691f45538301bcefa466590dda1cc84cbd7b47df3c9"

      def install
        bin.install "certsponge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.1/certsponge_darwin_arm64.tar.gz"
      sha256 "a6a2c7a1418f27874c5b2460d3a165f5a0af9373698a0a0340b47cae1319e1d5"

      def install
        bin.install "certsponge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.1/certsponge_linux_arm64.tar.gz"
      sha256 "a5b840cc5fb8bbc648b5161ad062ae4a94933ff9a0f725920050f65c09f1bd76"

      def install
        bin.install "certsponge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.1/certsponge_linux_amd64.tar.gz"
      sha256 "eae9e4ed156432833d85de564343362a475a71432354cbe9c456c8196a625eb0"

      def install
        bin.install "certsponge"
      end
    end
  end
end
