# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certin < Formula
  desc "Certin is a Go library and CLI for quickly creating keys and certificates for use as test fixtures."
  homepage "https://github.com/joemiller/certin"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certin/releases/download/v0.3.1/certin_darwin_amd64.tar.gz"
      sha256 "e4b804d214daf22082066f744c287b8e4879e893a2c44f062bd4edb73a5064f7"

      def install
        bin.install "certin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certin/releases/download/v0.3.1/certin_linux_amd64.tar.gz"
      sha256 "dec45602424619121d6af4b97f4ae89851975ccf546ee995ec9e60dc2bea538d"

      def install
        bin.install "certin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/certin/releases/download/v0.3.1/certin_linux_arm64.tar.gz"
      sha256 "1097da7a078b7c60b4d1cd3a41fa6674d40785f2a78c88c34ec30b3a15c24b89"

      def install
        bin.install "certin"
      end
    end
  end
end
