# This file was generated by GoReleaser. DO NOT EDIT.
class Certin < Formula
  desc "Certin is a Go library and CLI for quickly creating keys and certificates for use as test fixtures."
  homepage "https://github.com/joemiller/certin"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joemiller/certin/releases/download/v0.0.4/certin_darwin_amd64.tar.gz"
    sha256 "724a5c04263dffef333369e023efcf23964ca7f62433da3ec662ff56ec2324ea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certin/releases/download/v0.0.4/certin_linux_amd64.tar.gz"
      sha256 "f02e1d90f0b67d7042c637ae63e448f47704fd3e111168dead410114a144f063"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joemiller/certin/releases/download/v0.0.4/certin_linux_arm64.tar.gz"
        sha256 "d7f53938fbaffc4c4c041f720a9d0968bc7dac02735a4e466f44c2fa69840373"
      else
      end
    end
  end

  def install
    bin.install "certin"
  end
end
