# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certsponge < Formula
  desc "Utility for splitting Vault's PKI output into one or more files containing the private key, certificate, and CA data"
  homepage "https://github.com/joemiller/certsponge"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.2/certsponge_darwin_amd64.tar.gz"
      sha256 "a63a4b98699730afe2fe34ac57f0bf092494a7df86bacc6071c1fd1b604151b3"

      def install
        bin.install "certsponge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.2/certsponge_darwin_arm64.tar.gz"
      sha256 "615f317e09fde8f5c67e46df12995df55d04fc4f5668db21015a735d484a5ee3"

      def install
        bin.install "certsponge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.2/certsponge_linux_arm64.tar.gz"
      sha256 "4a69b341c3349477dbe96c65b5073850a959b2aced97439a0729bc1d0168d71b"

      def install
        bin.install "certsponge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/certsponge/releases/download/v0.0.2/certsponge_linux_amd64.tar.gz"
      sha256 "2c0233eb8a59f4c98669921192146c87da4b462f6e754b3d56b22567ce435bff"

      def install
        bin.install "certsponge"
      end
    end
  end
end
