# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmachine < Formula
  desc "Manage cloud machines on Google Cloud Platform"
  homepage "https://github.com/joemiller/gmachine"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.2/gmachine_darwin_arm64.tar.gz"
      sha256 "c4c9bafde9fbe074825ffdd97cdac04bbf8817b6f8304af5469a84f2c0c3c0fc"

      def install
        bin.install "gmachine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.2/gmachine_darwin_amd64.tar.gz"
      sha256 "f795f32decd32a57992654c03901a79bed4ce3e656e77d10ba2235108e114146"

      def install
        bin.install "gmachine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.2/gmachine_linux_amd64.tar.gz"
      sha256 "1624b803ae60aee8b0ef024acde0b5fe4d7199700af294f0de115d02618b5ab3"

      def install
        bin.install "gmachine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.2/gmachine_linux_arm64.tar.gz"
      sha256 "e2f70499bd02634422136ee875a3d86b802d04ed7bd6dbad8ff7aaf83091d48c"

      def install
        bin.install "gmachine"
      end
    end
  end
end
