# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmachine < Formula
  desc "Manage cloud machines on Google Cloud Platform"
  homepage "https://github.com/joemiller/gmachine"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.4/gmachine_darwin_arm64.tar.gz"
      sha256 "556a166a5be50050aa1c573f91d14cec2f4d26407c7a3aab5b5ee1e8fd718932"

      def install
        bin.install "gmachine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.4/gmachine_darwin_amd64.tar.gz"
      sha256 "0d23de3e1dda8f171a1c3f908a022db5f9b1854f272f35a6e6dbd9b14dea4677"

      def install
        bin.install "gmachine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.4/gmachine_linux_arm64.tar.gz"
      sha256 "ce64633d844ec6d3a8a9133f2c370def701d1f8f38e8370dbe9ba6432a61f85d"

      def install
        bin.install "gmachine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/gmachine/releases/download/v0.0.4/gmachine_linux_amd64.tar.gz"
      sha256 "1d22efa98232f920cfb83cb39c16ece0bb813b62c0137816f0137c0bd86d6db3"

      def install
        bin.install "gmachine"
      end
    end
  end
end
