# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenHelper < Formula
  desc "Cross-platform @hashicorp Vault token helper"
  homepage "https://github.com/joemiller/vault-token-helper"
  version "0.3.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joemiller/vault-token-helper/releases/download/v0.3.2/vault-token-helper_0.3.2_darwin_amd64.tar.gz"
    sha256 "caf67d855e6d07764c55dbbad317c0d6b27305ba8958cce396201478f49e10b7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/vault-token-helper/releases/download/v0.3.2/vault-token-helper_0.3.2_linux_amd64.tar.gz"
      sha256 "6e592b0315fd7642ea78f259c822cd06222405ba25576ee61e95d2b298a59b6e"
    end
  end
  
  depends_on "vault"

  def install
    bin.install "vault-token-helper"
  end

  def caveats; <<~EOS
    Run this to create the ~/.vault file. This will instruct vault to use the token helper:
    
      vault-token-helper enable
  EOS
  end
end
