# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenHelper < Formula
  desc "Cross-platform @hashicorp Vault token helper"
  homepage "https://github.com/joemiller/vault-token-helper"
  version "0.0.5"

  if OS.mac?
    url "https://github.com/joemiller/vault-token-helper/releases/download/v0.0.5/vault-token-helper_0.0.5_darwin_amd64.tar.gz"
    sha256 "6f7cd780cb9fe9553fd7e7bc18353f69919484c5b86f05e9b7f9ecd24bf3023c"
  elsif OS.linux?
    url "https://github.com/joemiller/vault-token-helper/releases/download/v0.0.5/vault-token-helper_0.0.5_linux_amd64.tar.gz"
    sha256 "c8eb57aae6ff55f1e169a35341370c23c329a54c4ae6ac0c22e59094673d633e"
  end
  
  depends_on "vault"

  def install
    bin.install "vault-token-helper"
  end

  def caveats; <<~EOS
    Run this to create the ~/.vault file. This will instruct vault to use the token helper:
    
      vault-token-helper enable
  EOS
  end
end
