# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenHelper < Formula
  desc "Cross-platform @hashicorp Vault token helper"
  homepage "https://github.com/joemiller/vault-token-helper"
  version "0.2.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/joemiller/vault-token-helper/releases/download/v0.2.6/vault-token-helper_0.2.6_darwin_amd64.tar.gz"
    sha256 "bbfa4405fe9b22b21d6ff39caeddf12029b868149c5ab269527b181c4717ad97"
  elsif OS.linux?
    url "https://github.com/joemiller/vault-token-helper/releases/download/v0.2.6/vault-token-helper_0.2.6_linux_amd64.tar.gz"
    sha256 "9f128d23c78ec3ebeb8ddaa5dbe0d2940766403a1081f1753467d2f6df73b182"
  end
  
  depends_on "vault"

  def install
    bin.install "vault-token-helper"
  end

  def caveats; <<~EOS
    Run this to create the ~/.vault file. This will instruct vault to use the token helper:
    
      vault-token-helper enable
  EOS
  end
end
