# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YkAttestVerify < Formula
  desc "Validate and enforce policy on YubiKey PIV and OpenPGP attestation certificates"
  homepage "https://github.com/joemiller/yk-attest-verify"
  version "0.2.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.9/yk-attest-verify_Darwin_amd64.tar.gz"
      sha256 "14e5d0a7075fca95bff6e5df207889173b986b829132e5c0356dea876a4e2024"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.9/yk-attest-verify_Darwin_arm64.tar.gz"
      sha256 "844b23ccb5e64a366fc539d4b71c4e0061536a750e1337e40352d9dec90ac8fd"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.9/yk-attest-verify_Linux_arm64.tar.gz"
      sha256 "4ccec1600c37d8650e7cb72f73a8ce04f271c5a79a5d9a57a910788a804bf858"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.9/yk-attest-verify_Linux_amd64.tar.gz"
      sha256 "076240f22643e679a3dedaff0b00fc742b47e7fbe383b7ceabf12d5e7f62f5e1"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end
end
