# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YkAttestVerify < Formula
  desc "Validate and enforce policy on YubiKey PIV and OpenPGP attestation certificates"
  homepage "https://github.com/joemiller/yk-attest-verify"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.1.0/yk-attest-verify_Darwin_amd64.tar.gz"
      sha256 "dfe54721e9ebd8982b3e8649c214ca1c3a7cdf2d4ef6c8d3153e67821b7748b4"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.1.0/yk-attest-verify_Darwin_arm64.tar.gz"
      sha256 "d43d0bfadcb9a0ce0763bc1d027cb186cdf98ffe73f389f4a22220811cd1b28e"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.1.0/yk-attest-verify_Linux_amd64.tar.gz"
      sha256 "1fcb0095f750b5de72c8a41d57f9c6a5a7876e141b82f08b0f2dbdd699c5bd76"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.1.0/yk-attest-verify_Linux_arm64.tar.gz"
      sha256 "3c359cb7834e10710d5f1cb1cef820d4dc88f3db93448ef4ceea80b4620ca435"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end
end
