# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YkAttestVerify < Formula
  desc "Validate and enforce policy on YubiKey PIV and OpenPGP attestation certificates"
  homepage "https://github.com/joemiller/yk-attest-verify"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.1/yk-attest-verify_Darwin_amd64.tar.gz"
      sha256 "bb7aa3f87cf3d4e00d20f01d09509f02d6812445634dcc8fd5a2e5796de4ad8e"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.1/yk-attest-verify_Darwin_arm64.tar.gz"
      sha256 "e1669c1497945a091192ca8b238c46603755901f382dcf1f0c879d2a562eaa10"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.1/yk-attest-verify_Linux_amd64.tar.gz"
      sha256 "8fdb0f87a59791843bd95a8776e1b6b22b382f47fff83a8d0cb3dfa33b63f4ce"

      def install
        bin.install "yk-attest-verify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joemiller/yk-attest-verify/releases/download/v0.2.1/yk-attest-verify_Linux_arm64.tar.gz"
      sha256 "73a8a21ff0b9cee12381b3bf5887abb2cb3cc1d37e66fd0707a2256f993fd93b"

      def install
        bin.install "yk-attest-verify"
      end
    end
  end
end
